$pdf_mode = 4; # LuaLaTeX
$lualatex = 'lualatex -interaction=nonstopmode -synctex=1 %O %S';
$bibtex_use = 2;
$aux_dir = 'build';
$out_dir = '';
$emulate_aux = 1;
$clean_ext = 'aux bbl bcf blg fdb_latexmk fls idx ilg ind log out run.xml synctex.gz toc xdv';
